/// Models for the Client community surface (feed + leaderboard). Mirror the
/// existing branch-scoped endpoints (ADR-019):
///   GET  /api/community/feed?cursor&limit      → { posts[], nextCursor }
///   POST /api/community/posts/[id]/react       → { reacted }
///   POST /api/community/posts/[id]/comments    → CommunityComment
///   GET  /api/community/leaderboard            → CompoundExercise[]
///   GET  /api/community/leaderboard?exerciseId  → LeaderboardEntry[]
library;

double? _asDouble(Object? v) =>
    v == null ? null : (v is num ? v.toDouble() : (v is String ? double.tryParse(v) : null));

int _asInt(Object? v, [int fallback = 0]) =>
    v is num ? v.toInt() : (v is String ? int.tryParse(v) ?? fallback : fallback);

int? _asIntOrNull(Object? v) =>
    v == null ? null : (v is num ? v.toInt() : (v is String ? int.tryParse(v) : null));

DateTime? _asDate(Object? v) =>
    v is String && v.isNotEmpty ? DateTime.tryParse(v)?.toLocal() : null;

String? _nameOf(Map? user) {
  if (user == null) return null;
  final n = '${user['firstName'] ?? ''} ${user['lastName'] ?? ''}'.trim();
  return n.isEmpty ? null : n;
}

/// The `client { id, user { firstName, lastName, profileImageUrl } }` block that
/// appears on posts and comments.
class CommunityAuthor {
  const CommunityAuthor({required this.clientProfileId, required this.name, this.photoUrl});

  final String clientProfileId;
  final String name;
  final String? photoUrl;

  factory CommunityAuthor.fromClient(Object? raw) {
    final client = raw is Map ? raw : const {};
    final user = client['user'] as Map?;
    return CommunityAuthor(
      clientProfileId: (client['id'] ?? '') as String,
      name: _nameOf(user) ?? 'Member',
      photoUrl: user?['profileImageUrl'] as String?,
    );
  }
}

class CommunityComment {
  const CommunityComment({
    required this.id,
    required this.content,
    required this.createdAt,
    required this.author,
  });

  final String id;
  final String content;
  final DateTime? createdAt;
  final CommunityAuthor author;

  factory CommunityComment.fromJson(Map<String, dynamic> json) => CommunityComment(
        id: (json['id'] ?? '') as String,
        content: (json['content'] ?? '') as String,
        createdAt: _asDate(json['createdAt']),
        author: CommunityAuthor.fromClient(json['client']),
      );
}

class CommunityPost {
  const CommunityPost({
    required this.id,
    required this.author,
    required this.content,
    required this.exerciseName,
    required this.weightKg,
    required this.reps,
    required this.isAutoGenerated,
    required this.createdAt,
    required this.reactedClientProfileIds,
    required this.reactionCount,
    required this.commentCount,
    required this.comments,
  });

  final String id;
  final CommunityAuthor author;
  final String? content;
  final String? exerciseName;
  final double? weightKg;
  final int? reps;
  final bool isAutoGenerated;
  final DateTime? createdAt;
  final List<String> reactedClientProfileIds;
  final int reactionCount;
  final int commentCount;
  final List<CommunityComment> comments;

  bool reactedBy(String? myClientProfileId) =>
      myClientProfileId != null && reactedClientProfileIds.contains(myClientProfileId);

  /// PR-style auto post → a "Bench Press · 80kg × 5" headline.
  String? get prHeadline {
    if (exerciseName == null) return null;
    final parts = <String>[exerciseName!];
    if (weightKg != null) {
      final w = weightKg!;
      parts.add('${w == w.roundToDouble() ? w.toInt() : w}kg');
    }
    if (reps != null) parts.add('× $reps');
    return parts.join(' · ');
  }

  factory CommunityPost.fromJson(Map<String, dynamic> json) {
    final reactions = (json['reactions'] as List? ?? const [])
        .whereType<Map>()
        .map((m) => (m['clientProfileId'] ?? '').toString())
        .where((s) => s.isNotEmpty)
        .toList();
    final comments = (json['comments'] as List? ?? const [])
        .whereType<Map>()
        .map((m) => CommunityComment.fromJson(Map<String, dynamic>.from(m)))
        .toList();
    final count = json['_count'] as Map?;
    final exercise = json['exercise'] as Map?;
    return CommunityPost(
      id: (json['id'] ?? '') as String,
      author: CommunityAuthor.fromClient(json['client']),
      content: json['content'] as String?,
      exerciseName: exercise?['name'] as String?,
      weightKg: _asDouble(json['weightKg']),
      reps: _asIntOrNull(json['reps']),
      isAutoGenerated: json['isAutoGenerated'] == true,
      createdAt: _asDate(json['createdAt']),
      reactedClientProfileIds: reactions,
      reactionCount: _asInt(count?['reactions'], reactions.length),
      commentCount: _asInt(count?['comments'], comments.length),
      comments: comments,
    );
  }

  CommunityPost copyWith({
    List<String>? reactedClientProfileIds,
    int? reactionCount,
    int? commentCount,
    List<CommunityComment>? comments,
  }) =>
      CommunityPost(
        id: id,
        author: author,
        content: content,
        exerciseName: exerciseName,
        weightKg: weightKg,
        reps: reps,
        isAutoGenerated: isAutoGenerated,
        createdAt: createdAt,
        reactedClientProfileIds: reactedClientProfileIds ?? this.reactedClientProfileIds,
        reactionCount: reactionCount ?? this.reactionCount,
        commentCount: commentCount ?? this.commentCount,
        comments: comments ?? this.comments,
      );

  /// Returns a copy reflecting [reacted] for [myId], adjusting the count.
  CommunityPost withReaction(String myId, bool reacted) {
    final has = reactedClientProfileIds.contains(myId);
    if (has == reacted) return this;
    final ids = [...reactedClientProfileIds];
    if (reacted) {
      ids.add(myId);
    } else {
      ids.remove(myId);
    }
    return copyWith(
      reactedClientProfileIds: ids,
      reactionCount: (reactionCount + (reacted ? 1 : -1)).clamp(0, 1 << 30),
    );
  }

  CommunityPost withAddedComment(CommunityComment c) =>
      copyWith(comments: [...comments, c], commentCount: commentCount + 1);

  CommunityPost withRemovedComment(String commentId) => copyWith(
        comments: comments.where((c) => c.id != commentId).toList(),
        commentCount: (commentCount - 1).clamp(0, 1 << 30),
      );
}

/// A compound exercise shown as a leaderboard tab/selector.
class CompoundExercise {
  const CompoundExercise({required this.id, required this.name, this.muscleGroup});
  final String id;
  final String name;
  final String? muscleGroup;

  factory CompoundExercise.fromJson(Map<String, dynamic> json) => CompoundExercise(
        id: (json['id'] ?? '') as String,
        name: (json['name'] ?? 'Exercise') as String,
        muscleGroup: json['targetMuscleGroup'] as String?,
      );
}

class LeaderboardEntry {
  const LeaderboardEntry({
    required this.rank,
    required this.clientProfileId,
    required this.name,
    required this.maxWeightKg,
    this.photoUrl,
    this.reps,
    this.achievedAt,
  });

  final int rank;
  final String clientProfileId;
  final String name;
  final double maxWeightKg;
  final String? photoUrl;
  final int? reps;
  final DateTime? achievedAt;

  factory LeaderboardEntry.fromJson(Map<String, dynamic> json, int fallbackRank) =>
      LeaderboardEntry(
        rank: _asIntOrNull(json['rank']) ?? fallbackRank,
        clientProfileId: (json['clientProfileId'] ?? '') as String,
        name: '${json['firstName'] ?? ''} ${json['lastName'] ?? ''}'.trim().isEmpty
            ? 'Member'
            : '${json['firstName'] ?? ''} ${json['lastName'] ?? ''}'.trim(),
        photoUrl: json['profileImageUrl'] as String?,
        maxWeightKg: _asDouble(json['maxWeightKg']) ?? 0,
        reps: _asIntOrNull(json['reps']),
        achievedAt: _asDate(json['achievedAt']),
      );
}
