import { prisma } from '@/lib/prisma';
import { auditLog } from '@/lib/audit';
import { AppError } from '@/lib/errors';

// ─── Types ────────────────────────────────────────────

const POST_INCLUDE = {
  client: {
    include: {
      user: { select: { firstName: true, lastName: true, profileImageUrl: true } },
    },
  },
  exercise: { select: { id: true, name: true } },
  reactions: {
    select: { id: true, clientProfileId: true },
  },
  comments: {
    orderBy: { createdAt: 'asc' as const },
    include: {
      client: {
        include: {
          user: { select: { firstName: true, lastName: true, profileImageUrl: true } },
        },
      },
    },
  },
  _count: { select: { reactions: true, comments: true } },
};

// ─── Feed ─────────────────────────────────────────────

export async function getFeed({
  branchId,
  cursor,
  limit = 20,
}: {
  branchId: string;
  cursor?: string;
  limit?: number;
}) {
  const posts = await prisma.communityPost.findMany({
    where: {
      branchId,
      isHidden: false,
    },
    orderBy: { createdAt: 'desc' },
    take: limit + 1,
    cursor: cursor ? { id: cursor } : undefined,
    include: POST_INCLUDE,
  });

  const hasNextPage = posts.length > limit;
  if (hasNextPage) posts.pop();

  return {
    posts,
    nextCursor: hasNextPage ? posts[posts.length - 1]?.id : null,
  };
}

// ─── Create Post ──────────────────────────────────────

export async function createPost({
  branchId,
  clientProfileId,
  content,
  exerciseId,
  weightKg,
  reps,
  isAutoGenerated = false,
  actorId,
}: {
  branchId: string;
  clientProfileId: string;
  content?: string;
  exerciseId?: string;
  weightKg?: number;
  reps?: number;
  isAutoGenerated?: boolean;
  actorId: string;
}) {
  // Verify client belongs to branch
  const client = await prisma.clientProfile.findFirst({
    where: { id: clientProfileId, branchId },
  });
  if (!client) throw new AppError('NOT_FOUND', 'Client not found', 404);

  const post = await prisma.communityPost.create({
    data: {
      branchId,
      clientProfileId,
      content,
      exerciseId,
      weightKg,
      reps,
      isAutoGenerated,
    },
    include: POST_INCLUDE,
  });

  await auditLog({
    action: 'COMMUNITY_POST_CREATED',
    actorId,
    subjectType: 'CommunityPost',
    subjectId: post.id,
    newValue: { isAutoGenerated, exerciseId, weightKg },
    branchId,
  });

  return post;
}

// ─── Delete / Hide Post ───────────────────────────────

export async function deletePost({
  postId,
  branchId,
  actorClientProfileId,
  actorId,
}: {
  postId: string;
  branchId: string;
  actorClientProfileId: string;
  actorId: string;
}) {
  const post = await prisma.communityPost.findFirst({
    where: { id: postId, branchId },
  });
  if (!post) throw new AppError('NOT_FOUND', 'Post not found', 404);

  // Only the post owner can delete
  if (post.clientProfileId !== actorClientProfileId) {
    throw new AppError('FORBIDDEN', "Cannot delete another user's post", 403);
  }

  await prisma.communityPost.update({
    where: { id: postId },
    data: { isHidden: true },
  });

  await auditLog({
    action: 'COMMUNITY_POST_DELETED',
    actorId,
    subjectType: 'CommunityPost',
    subjectId: postId,
    branchId,
  });
}

// ─── Toggle Reaction (Praise) ─────────────────────────

export async function toggleReaction({
  postId,
  branchId,
  clientProfileId,
}: {
  postId: string;
  branchId: string;
  clientProfileId: string;
}) {
  const post = await prisma.communityPost.findFirst({
    where: { id: postId, branchId, isHidden: false },
  });
  if (!post) throw new AppError('NOT_FOUND', 'Post not found', 404);

  const existing = await prisma.communityReaction.findUnique({
    where: { postId_clientProfileId: { postId, clientProfileId } },
  });

  if (existing) {
    await prisma.communityReaction.delete({ where: { id: existing.id } });
    return { reacted: false };
  }

  await prisma.communityReaction.create({
    data: { postId, clientProfileId },
  });
  return { reacted: true };
}

// ─── Add Comment ──────────────────────────────────────

export async function addComment({
  postId,
  branchId,
  clientProfileId,
  content,
  actorId,
}: {
  postId: string;
  branchId: string;
  clientProfileId: string;
  content: string;
  actorId: string;
}) {
  const post = await prisma.communityPost.findFirst({
    where: { id: postId, branchId, isHidden: false },
  });
  if (!post) throw new AppError('NOT_FOUND', 'Post not found', 404);

  const comment = await prisma.communityComment.create({
    data: { postId, clientProfileId, content },
    include: {
      client: {
        include: {
          user: { select: { firstName: true, lastName: true, profileImageUrl: true } },
        },
      },
    },
  });

  await auditLog({
    action: 'COMMUNITY_COMMENT_ADDED',
    actorId,
    subjectType: 'CommunityComment',
    subjectId: comment.id,
    newValue: { postId },
    branchId,
  });

  return comment;
}

// ─── Delete Comment ───────────────────────────────────

export async function deleteComment({
  commentId,
  branchId,
  actorClientProfileId,
  actorId,
}: {
  commentId: string;
  branchId: string;
  actorClientProfileId: string;
  actorId: string;
}) {
  const comment = await prisma.communityComment.findFirst({
    where: {
      id: commentId,
      post: { branchId },
    },
  });
  if (!comment) throw new AppError('NOT_FOUND', 'Comment not found', 404);

  if (comment.clientProfileId !== actorClientProfileId) {
    throw new AppError('FORBIDDEN', "Cannot delete another user's comment", 403);
  }

  await prisma.communityComment.delete({ where: { id: commentId } });

  await auditLog({
    action: 'COMMUNITY_COMMENT_DELETED',
    actorId,
    subjectType: 'CommunityComment',
    subjectId: commentId,
    branchId,
  });
}
