import { prisma } from '@/lib/prisma';
import type { LiveSessionRow, PrFeedRow } from '@/services/tv-dashboard.service';
import { getTvControlState } from '@/services/tv-control.service';

export interface TvLivePayload {
  generatedAt: string;
  liveNow: { count: number; sessions: LiveSessionRow[] };
  latestPRs: PrFeedRow[];
  control: {
    pinnedPanel: string | null;
    shoutout: { message: string; expiresAt: string } | null;
  };
}

interface CacheEntry {
  expiresAt: number;
  payload: TvLivePayload;
}
const cache = new Map<string, CacheEntry>();
const CACHE_TTL_MS = 10_000;

/** Test/debug helper. */
export function clearTvLiveCache(): void {
  cache.clear();
}

function fullName(firstName: string, lastName: string): string {
  return `${firstName} ${lastName}`.trim();
}

/**
 * Fast-refresh subset of the TV dashboard: `liveNow` (in-progress sessions),
 * `latestPRs` (last 7 days of auto-generated PR posts), and the live `control`
 * state (pin + shoutout). The TV polls this every ~10s — the dashboard
 * fetches the heavy aggregates at 60s, and this endpoint covers everything
 * that benefits from sub-minute freshness.
 */
export async function getTvLive({ branchId }: { branchId: string }): Promise<TvLivePayload> {
  const cached = cache.get(branchId);
  if (cached && cached.expiresAt > Date.now()) {
    return cached.payload;
  }

  const [live, posts, control] = await Promise.all([
    prisma.sessionInstance.findMany({
      where: { branchId, status: 'IN_PROGRESS' },
      orderBy: { startedAt: 'asc' },
      take: 20,
      select: {
        startedAt: true,
        client: {
          select: {
            showOnTv: true,
            user: { select: { firstName: true, lastName: true } },
          },
        },
        trainer: {
          select: { user: { select: { firstName: true, lastName: true } } },
        },
      },
    }),
    prisma.communityPost.findMany({
      where: {
        branchId,
        isAutoGenerated: true,
        isHidden: false,
        createdAt: { gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
        exerciseId: { not: null },
        weightKg: { not: null },
        client: { showOnTv: true },
      },
      orderBy: { createdAt: 'desc' },
      take: 10,
      select: {
        weightKg: true,
        reps: true,
        createdAt: true,
        exercise: { select: { name: true } },
        client: {
          select: {
            user: { select: { firstName: true, lastName: true, profileImageUrl: true } },
          },
        },
      },
    }),
    getTvControlState(branchId),
  ]);

  const sessions: LiveSessionRow[] = live
    .filter((s) => s.client.showOnTv && s.startedAt)
    .map((s) => ({
      trainerName: fullName(s.trainer.user.firstName, s.trainer.user.lastName),
      clientName: fullName(s.client.user.firstName, s.client.user.lastName),
      startedAt: s.startedAt!.toISOString(),
    }));

  const latestPRs: PrFeedRow[] = posts
    .filter((p) => p.exercise && p.weightKg != null)
    .map((p) => ({
      clientName: fullName(p.client.user.firstName, p.client.user.lastName),
      profileImageUrl: p.client.user.profileImageUrl,
      exerciseName: p.exercise!.name,
      weightKg: p.weightKg!,
      reps: p.reps,
      achievedAt: p.createdAt.toISOString(),
    }));

  const payload: TvLivePayload = {
    generatedAt: new Date().toISOString(),
    liveNow: { count: live.length, sessions },
    latestPRs,
    control,
  };

  cache.set(branchId, { expiresAt: Date.now() + CACHE_TTL_MS, payload });
  return payload;
}
