'use client';

import { useCallback, useEffect, useState } from 'react';
import { useSession } from 'next-auth/react';
import { Heart, MessageCircle, Trophy, Trash2, Send, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { formatDistanceToNow } from 'date-fns';

// ─── Types ────────────────────────────────────────────

interface PostClient {
  id: string;
  user: { firstName: string; lastName: string; profileImageUrl: string | null };
}

interface Comment {
  id: string;
  content: string;
  createdAt: string;
  client: PostClient;
}

interface Post {
  id: string;
  content: string | null;
  exerciseId: string | null;
  weightKg: number | null;
  reps: number | null;
  isAutoGenerated: boolean;
  isHidden: boolean;
  createdAt: string;
  client: PostClient;
  exercise: { id: string; name: string } | null;
  reactions: { id: string; clientProfileId: string }[];
  comments: Comment[];
  _count: { reactions: number; comments: number };
}

// ─── Helpers ──────────────────────────────────────────

function Avatar({ name, imageUrl }: { name: string; imageUrl?: string | null }) {
  if (imageUrl) {
    return <img src={imageUrl} alt={name} className="w-9 h-9 rounded-full object-cover" />;
  }
  const initials = name
    .split(' ')
    .map((n) => n[0])
    .join('')
    .slice(0, 2)
    .toUpperCase();
  return (
    <div className="w-9 h-9 rounded-full bg-orange-500/20 flex items-center justify-center text-orange-400 text-xs font-semibold flex-shrink-0">
      {initials}
    </div>
  );
}

// ─── Post Card ────────────────────────────────────────

function PostCard({
  post,
  myClientProfileId,
  onReact,
  onComment,
  onDelete,
  onDeleteComment,
}: {
  post: Post;
  myClientProfileId: string | null | undefined;
  onReact: (postId: string) => void;
  onComment: (postId: string, content: string) => Promise<void>;
  onDelete: (postId: string) => void;
  onDeleteComment: (postId: string, commentId: string) => void;
}) {
  const [showComments, setShowComments] = useState(false);
  const [commentText, setCommentText] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const isReacted = post.reactions.some((r) => r.clientProfileId === myClientProfileId);
  const isOwner = post.client.id === myClientProfileId;

  const fullName = `${post.client.user.firstName} ${post.client.user.lastName}`;

  async function handleComment() {
    if (!commentText.trim()) return;
    setSubmitting(true);
    try {
      await onComment(post.id, commentText.trim());
      setCommentText('');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Card className="p-4 space-y-3">
      {/* Header */}
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-3">
          <Avatar name={fullName} imageUrl={post.client.user.profileImageUrl} />
          <div>
            <p className="font-semibold text-sm">{fullName}</p>
            <p className="text-xs text-muted-foreground">
              {formatDistanceToNow(new Date(post.createdAt), { addSuffix: true })}
            </p>
          </div>
        </div>
        {isOwner && (
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7 text-muted-foreground hover:text-destructive"
            onClick={() => onDelete(post.id)}
          >
            <Trash2 className="h-3.5 w-3.5" />
          </Button>
        )}
      </div>

      {/* PR Achievement */}
      {post.isAutoGenerated && post.exercise && (
        <div className="flex items-center gap-2 bg-orange-500/10 rounded-lg px-3 py-2">
          <Trophy className="h-4 w-4 text-orange-400 flex-shrink-0" />
          <p className="text-sm font-medium text-orange-300">
            New PR on {post.exercise.name}
            {post.weightKg != null && <span className="ml-1 font-bold">{post.weightKg} kg</span>}
            {post.reps != null && (
              <span className="ml-1 text-orange-400/80">× {post.reps} reps</span>
            )}
          </p>
        </div>
      )}

      {/* Caption */}
      {post.content && <p className="text-sm text-foreground">{post.content}</p>}

      {/* Reaction & comment counts */}
      {(post._count.reactions > 0 || post._count.comments > 0) && (
        <div className="flex items-center gap-4 text-xs text-muted-foreground">
          {post._count.reactions > 0 && (
            <span className="flex items-center gap-1">
              <Heart className="h-3 w-3 fill-red-400 text-red-400" />
              {post._count.reactions}
            </span>
          )}
          {post._count.comments > 0 && (
            <button
              className="flex items-center gap-1 hover:text-foreground transition-colors"
              onClick={() => setShowComments((s) => !s)}
            >
              <MessageCircle className="h-3 w-3" />
              {post._count.comments} comment{post._count.comments !== 1 ? 's' : ''}
            </button>
          )}
        </div>
      )}

      {/* Action bar */}
      <div className="flex items-center gap-2 border-t pt-2">
        <Button
          variant="ghost"
          size="sm"
          className={`flex-1 gap-2 ${isReacted ? 'text-red-400' : 'text-muted-foreground'}`}
          onClick={() => onReact(post.id)}
          disabled={!myClientProfileId}
        >
          <Heart className={`h-4 w-4 ${isReacted ? 'fill-red-400' : ''}`} />
          Praise
        </Button>
        <Button
          variant="ghost"
          size="sm"
          className="flex-1 gap-2 text-muted-foreground"
          onClick={() => setShowComments((s) => !s)}
        >
          <MessageCircle className="h-4 w-4" />
          Comment
          {showComments && <ChevronDown className="h-3 w-3" />}
        </Button>
      </div>

      {/* Comments section */}
      {showComments && (
        <div className="space-y-3 border-t pt-3">
          {post.comments.map((c) => (
            <div key={c.id} className="flex items-start gap-2 group">
              <Avatar
                name={`${c.client.user.firstName} ${c.client.user.lastName}`}
                imageUrl={c.client.user.profileImageUrl}
              />
              <div className="flex-1 min-w-0">
                <div className="bg-muted rounded-xl px-3 py-2">
                  <p className="text-xs font-semibold">
                    {c.client.user.firstName} {c.client.user.lastName}
                  </p>
                  <p className="text-sm">{c.content}</p>
                </div>
                <p className="text-xs text-muted-foreground mt-0.5 ml-3">
                  {formatDistanceToNow(new Date(c.createdAt), { addSuffix: true })}
                </p>
              </div>
              {c.client.id === myClientProfileId && (
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-6 w-6 opacity-0 group-hover:opacity-100 text-muted-foreground hover:text-destructive"
                  onClick={() => onDeleteComment(post.id, c.id)}
                >
                  <Trash2 className="h-3 w-3" />
                </Button>
              )}
            </div>
          ))}

          {/* Add comment input */}
          {myClientProfileId && (
            <div className="flex items-end gap-2">
              <Textarea
                value={commentText}
                onChange={(e) => setCommentText(e.target.value)}
                placeholder="Write a comment…"
                className="resize-none text-sm min-h-[60px]"
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleComment();
                  }
                }}
              />
              <Button
                size="icon"
                className="mb-0.5 bg-blue-600 hover:bg-blue-700"
                onClick={handleComment}
                disabled={submitting || !commentText.trim()}
              >
                <Send className="h-4 w-4" />
              </Button>
            </div>
          )}
        </div>
      )}
    </Card>
  );
}

// ─── Page ─────────────────────────────────────────────

export default function CommunityFeedPage() {
  const { data: session } = useSession();
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const myClientProfileId = session?.user?.clientProfileId;

  const fetchFeed = useCallback(async (cursor?: string) => {
    const url = `/api/community/feed${cursor ? `?cursor=${cursor}` : ''}`;
    const res = await fetch(url);
    const json = await res.json();
    return json.data as { posts: Post[]; nextCursor: string | null };
  }, []);

  useEffect(() => {
    fetchFeed()
      .then(({ posts, nextCursor }) => {
        setPosts(posts);
        setNextCursor(nextCursor);
      })
      .catch(() => toast.error('Failed to load feed'))
      .finally(() => setLoading(false));
  }, [fetchFeed]);

  async function loadMore() {
    if (!nextCursor || loadingMore) return;
    setLoadingMore(true);
    try {
      const { posts: more, nextCursor: nc } = await fetchFeed(nextCursor);
      setPosts((prev) => [...prev, ...more]);
      setNextCursor(nc);
    } catch {
      toast.error('Failed to load more posts');
    } finally {
      setLoadingMore(false);
    }
  }

  async function handleReact(postId: string) {
    const res = await fetch(`/api/community/posts/${postId}/react`, { method: 'POST' });
    const json = await res.json();
    if (!res.ok) {
      toast.error('Could not react');
      return;
    }

    const { reacted } = json.data;
    setPosts((prev) =>
      prev.map((p) => {
        if (p.id !== postId) return p;
        const filtered = p.reactions.filter((r) => r.clientProfileId !== myClientProfileId);
        return {
          ...p,
          reactions: reacted
            ? [...filtered, { id: 'optimistic', clientProfileId: myClientProfileId! }]
            : filtered,
          _count: {
            ...p._count,
            reactions: reacted ? p._count.reactions + 1 : p._count.reactions - 1,
          },
        };
      }),
    );
  }

  async function handleComment(postId: string, content: string) {
    const res = await fetch(`/api/community/posts/${postId}/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content }),
    });
    const json = await res.json();
    if (!res.ok) {
      toast.error('Failed to post comment');
      return;
    }

    const comment = json.data as Comment;
    setPosts((prev) =>
      prev.map((p) =>
        p.id === postId
          ? {
              ...p,
              comments: [...p.comments, comment],
              _count: { ...p._count, comments: p._count.comments + 1 },
            }
          : p,
      ),
    );
  }

  async function handleDelete(postId: string) {
    const res = await fetch(`/api/community/posts/${postId}`, { method: 'DELETE' });
    if (!res.ok) {
      toast.error('Could not delete post');
      return;
    }
    setPosts((prev) => prev.filter((p) => p.id !== postId));
    toast.success('Post removed');
  }

  function handleDeleteComment(postId: string, commentId: string) {
    fetch(`/api/community/posts/${postId}/comments/${commentId}`, { method: 'DELETE' })
      .then((res) => {
        if (!res.ok) throw new Error();
        setPosts((prev) =>
          prev.map((p) =>
            p.id === postId
              ? {
                  ...p,
                  comments: p.comments.filter((c) => c.id !== commentId),
                  _count: { ...p._count, comments: p._count.comments - 1 },
                }
              : p,
          ),
        );
      })
      .catch(() => toast.error('Failed to delete comment'));
  }

  if (loading) {
    return (
      <div className="max-w-xl mx-auto p-4 space-y-4">
        <Skeleton className="h-8 w-48" />
        {[1, 2, 3].map((i) => (
          <Skeleton key={i} className="h-40 w-full rounded-xl" />
        ))}
      </div>
    );
  }

  return (
    <div className="max-w-xl mx-auto p-4 space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Community</h1>
          <p className="text-sm text-muted-foreground">PRs, achievements & gym energy</p>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="gap-2"
          onClick={() => (window.location.href = '/community/leaderboard')}
        >
          <Trophy className="h-4 w-4" />
          Leaderboard
        </Button>
      </div>

      {/* Feed */}
      {posts.length === 0 ? (
        <div className="text-center py-16 text-muted-foreground">
          <Trophy className="h-10 w-10 mx-auto mb-3 opacity-30" />
          <p className="font-medium">No posts yet</p>
          <p className="text-sm mt-1">Hit a PR to get the community going!</p>
        </div>
      ) : (
        <div className="space-y-4">
          {posts.map((post) => (
            <PostCard
              key={post.id}
              post={post}
              myClientProfileId={myClientProfileId}
              onReact={handleReact}
              onComment={handleComment}
              onDelete={handleDelete}
              onDeleteComment={handleDeleteComment}
            />
          ))}
        </div>
      )}

      {/* Load more */}
      {nextCursor && (
        <div className="flex justify-center pt-2">
          <Button variant="outline" onClick={loadMore} disabled={loadingMore} className="gap-2">
            {loadingMore ? 'Loading…' : 'Load more'}
            <ChevronDown className="h-4 w-4" />
          </Button>
        </div>
      )}
    </div>
  );
}
