import 'package:flutter_test/flutter_test.dart';
import 'package:sector7_mobile/src/features/community/data/community_models.dart';

void main() {
  group('CommunityPost.fromJson', () {
    test('parses author, exercise PR, reactions, comments + counts', () {
      final p = CommunityPost.fromJson({
        'id': 'post_1',
        'content': 'New bench PR!',
        'isAutoGenerated': true,
        'createdAt': '2026-06-14T08:00:00.000Z',
        'weightKg': 80,
        'reps': 5,
        'client': {
          'id': 'cp_1',
          'user': {'firstName': 'Arun', 'lastName': 'Kumar', 'profileImageUrl': 'u'},
        },
        'exercise': {'id': 'ex_1', 'name': 'Bench Press'},
        'reactions': [
          {'id': 'r1', 'clientProfileId': 'cp_2'},
          {'id': 'r2', 'clientProfileId': 'cp_1'},
        ],
        'comments': [
          {
            'id': 'c1',
            'content': 'Beast!',
            'createdAt': '2026-06-14T09:00:00.000Z',
            'client': {
              'id': 'cp_2',
              'user': {'firstName': 'Bea', 'lastName': 'Lo'},
            },
          },
        ],
        '_count': {'reactions': 2, 'comments': 1},
      });

      expect(p.id, 'post_1');
      expect(p.author.name, 'Arun Kumar');
      expect(p.author.clientProfileId, 'cp_1');
      expect(p.exerciseName, 'Bench Press');
      expect(p.prHeadline, 'Bench Press · 80kg · × 5');
      expect(p.reactionCount, 2);
      expect(p.commentCount, 1);
      expect(p.comments.first.author.name, 'Bea Lo');
      expect(p.reactedBy('cp_1'), isTrue);
      expect(p.reactedBy('cp_99'), isFalse);
      expect(p.reactedBy(null), isFalse);
    });

    test('falls back to reactions/comments length when _count missing', () {
      final p = CommunityPost.fromJson({
        'id': 'post_2',
        'content': 'gm',
        'client': {
          'id': 'cp_3',
          'user': {'firstName': 'C', 'lastName': 'D'},
        },
        'reactions': [
          {'id': 'r', 'clientProfileId': 'cp_4'},
        ],
        'comments': [],
      });
      expect(p.reactionCount, 1);
      expect(p.commentCount, 0);
      expect(p.prHeadline, isNull); // no exercise
      expect(p.isAutoGenerated, isFalse);
    });
  });

  group('CommunityPost mutations', () {
    final base = CommunityPost.fromJson({
      'id': 'post_1',
      'client': {
        'id': 'cp_1',
        'user': {'firstName': 'A', 'lastName': 'B'},
      },
      'reactions': [],
      'comments': [],
      '_count': {'reactions': 0, 'comments': 0},
    });

    test('withReaction adds then removes the viewer, adjusting count', () {
      final liked = base.withReaction('cp_9', true);
      expect(liked.reactedBy('cp_9'), isTrue);
      expect(liked.reactionCount, 1);

      final unliked = liked.withReaction('cp_9', false);
      expect(unliked.reactedBy('cp_9'), isFalse);
      expect(unliked.reactionCount, 0);
    });

    test('withReaction is idempotent for the same state', () {
      final liked = base.withReaction('cp_9', true);
      final again = liked.withReaction('cp_9', true);
      expect(again.reactionCount, 1);
    });

    test('add then remove a comment keeps count in sync', () {
      final withComment = base.withAddedComment(
        const CommunityComment(
          id: 'c1',
          content: 'hi',
          createdAt: null,
          author: CommunityAuthor(clientProfileId: 'cp_2', name: 'Bea'),
        ),
      );
      expect(withComment.commentCount, 1);
      expect(withComment.comments, hasLength(1));

      final removed = withComment.withRemovedComment('c1');
      expect(removed.commentCount, 0);
      expect(removed.comments, isEmpty);
    });
  });

  group('LeaderboardEntry + CompoundExercise', () {
    test('parses an entry and uses fallback rank when absent', () {
      final e = LeaderboardEntry.fromJson({
        'clientProfileId': 'cp_1',
        'firstName': 'Arun',
        'lastName': 'Kumar',
        'maxWeightKg': 102.5,
        'reps': 3,
        'achievedAt': '2026-06-10T00:00:00.000Z',
      }, 4);
      expect(e.rank, 4);
      expect(e.name, 'Arun Kumar');
      expect(e.maxWeightKg, 102.5);
      expect(e.reps, 3);
    });

    test('prefers an explicit rank when present', () {
      final e = LeaderboardEntry.fromJson({
        'rank': 1,
        'clientProfileId': 'cp_1',
        'firstName': '',
        'lastName': '',
        'maxWeightKg': 60,
      }, 9);
      expect(e.rank, 1);
      expect(e.name, 'Member'); // blank name fallback
    });

    test('parses a compound exercise', () {
      final c = CompoundExercise.fromJson({
        'id': 'ex_1',
        'name': 'Deadlift',
        'targetMuscleGroup': 'Back',
      });
      expect(c.id, 'ex_1');
      expect(c.name, 'Deadlift');
      expect(c.muscleGroup, 'Back');
    });
  });
}
