import { NextResponse } from 'next/server';
import { ZodError, z } from 'zod';
import { getServerSession } from '@/lib/auth';
import { toErrorResponse, AppError } from '@/lib/errors';
import { workoutEntrySchema } from '@/lib/validators';
import { triggerWorkoutUpdatedEvent } from '@/lib/pusher';
import * as workoutService from '@/services/workout.service';

// Body shape: same as legacy /api/trainer/workouts minus the sessionInstanceId
// which now lives in the URL. `dirtyExerciseIds`/`removedExerciseIds` scope the
// write to what this device actually changed since its last sync (ADR-036) so a
// stale full-snapshot from a peer can't clobber concurrent edits. Both optional
// — when omitted the service falls back to full-replace (legacy callers).
// `removedSetsByExerciseId` narrows the scoping to per-set: within a dirty
// exercise only the named set numbers are deleted, so a peer's concurrent rows
// in the SAME exercise survive. When omitted (pre-per-set bundles) a dirty
// exercise's sets reconcile by absence, as before.
const bodySchema = z.object({
  exercises: z.array(workoutEntrySchema).min(1),
  dirtyExerciseIds: z.array(z.string()).optional(),
  removedExerciseIds: z.array(z.string()).optional(),
  removedSetsByExerciseId: z.record(z.string(), z.array(z.number().int().min(1))).optional(),
});

/**
 * POST /api/sessions/[id]/workouts
 *
 * Shared write path for workout logging — either the trainer or the client
 * of the session can save. Authorization is handled by assertSessionAccess
 * inside the service (matches /api/sessions/[id]/rest-timer pattern).
 */
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id: sessionInstanceId } = await params;
    const auth = await getServerSession();
    if (!auth) {
      return NextResponse.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, { status: 401 });
    }
    const { id: actorUserId, branchId, trainerProfileId, clientProfileId } = auth.user;
    if (!branchId) {
      throw new AppError('NO_BRANCH', 'User has no branch', 400);
    }

    const body = await req.json();
    const input = bodySchema.parse(body);

    const { workoutLogs, newBadges, autoGeneratedPostIds } = await workoutService.createWorkoutLogs(
      {
        sessionInstanceId,
        exercises: input.exercises,
        dirtyExerciseIds: input.dirtyExerciseIds,
        removedExerciseIds: input.removedExerciseIds,
        removedSetsByExerciseId: input.removedSetsByExerciseId,
        actorUserId,
        actorTrainerProfileId: trainerProfileId ?? null,
        actorClientProfileId: clientProfileId ?? null,
        branchId,
      },
    );

    // Notify the peer (trainer ↔ client) that the log changed so their UI
    // can refetch without polling. actorUserId lets the writer skip its
    // own echo. Fire-and-forget — never block the response on the broker.
    void triggerWorkoutUpdatedEvent(sessionInstanceId, {
      sessionId: sessionInstanceId,
      actorUserId,
      updatedAt: Date.now(),
    });

    return NextResponse.json(
      { data: workoutLogs, newBadges, autoGeneratedPostIds },
      { status: 201 },
    );
  } catch (err) {
    if (err instanceof ZodError) {
      return NextResponse.json(
        { error: 'Invalid payload', code: 'VALIDATION_ERROR', issues: err.issues },
        { status: 422 },
      );
    }
    console.error('[POST /api/sessions/[id]/workouts] Error:', err);
    const r = toErrorResponse(err);
    return NextResponse.json({ error: r.error, code: r.code }, { status: r.status });
  }
}
