import { NextResponse } from 'next/server';
import { ZodError, z } from 'zod';
import { getServerSession } from '@/lib/auth';
import { toErrorResponse, AppError } from '@/lib/errors';
import { workoutEntrySchema } from '@/lib/validators';
import * as workoutService from '@/services/workout.service';

// Body shape: same as legacy /api/trainer/workouts minus the sessionInstanceId
// which now lives in the URL.
const bodySchema = z.object({
  exercises: z.array(workoutEntrySchema).min(1),
});

/**
 * POST /api/sessions/[id]/workouts
 *
 * Shared write path for workout logging — either the trainer or the client
 * of the session can save. Authorization is handled by assertSessionAccess
 * inside the service (matches /api/sessions/[id]/rest-timer pattern).
 */
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id: sessionInstanceId } = await params;
    const auth = await getServerSession();
    if (!auth) {
      return NextResponse.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, { status: 401 });
    }
    const { id: actorUserId, branchId, trainerProfileId, clientProfileId } = auth.user;
    if (!branchId) {
      throw new AppError('NO_BRANCH', 'User has no branch', 400);
    }

    const body = await req.json();
    const input = bodySchema.parse(body);

    const { workoutLogs, newBadges, autoGeneratedPostIds } = await workoutService.createWorkoutLogs(
      {
        sessionInstanceId,
        exercises: input.exercises,
        actorUserId,
        actorTrainerProfileId: trainerProfileId ?? null,
        actorClientProfileId: clientProfileId ?? null,
        branchId,
      },
    );

    return NextResponse.json(
      { data: workoutLogs, newBadges, autoGeneratedPostIds },
      { status: 201 },
    );
  } catch (err) {
    if (err instanceof ZodError) {
      return NextResponse.json(
        { error: 'Invalid payload', code: 'VALIDATION_ERROR', issues: err.issues },
        { status: 422 },
      );
    }
    console.error('[POST /api/sessions/[id]/workouts] Error:', err);
    const r = toErrorResponse(err);
    return NextResponse.json({ error: r.error, code: r.code }, { status: r.status });
  }
}
