import { NextResponse } from 'next/server';
import { getServerSession, hasRole } from '@/lib/auth';
import { toErrorResponse } from '@/lib/errors';
import { createWorkoutSchema } from '@/lib/validators';
import * as workoutService from '@/services/workout.service';

/**
 * @deprecated Prefer POST /api/sessions/[id]/workouts (shared trainer/client
 * write path, ADR-036). This route stays alive for offline-sync clients that
 * already POST here; once that's migrated it can go.
 */
export async function POST(req: Request) {
  try {
    const session = await getServerSession();
    if (!session || !hasRole(session.user.roles, ['TRAINER', 'KICKBOXING_TRAINER'])) {
      return NextResponse.json({ error: 'Forbidden', code: 'FORBIDDEN' }, { status: 403 });
    }

    const trainerProfileId = session.user.trainerProfileId;
    if (!trainerProfileId) {
      return NextResponse.json(
        { error: 'No trainer profile', code: 'NO_PROFILE' },
        { status: 400 },
      );
    }

    const body = await req.json();
    const input = createWorkoutSchema.parse(body);

    const { workoutLogs, newBadges, autoGeneratedPostIds } = await workoutService.createWorkoutLogs(
      {
        sessionInstanceId: input.sessionInstanceId,
        exercises: input.exercises,
        actorUserId: session.user.id,
        actorTrainerProfileId: trainerProfileId,
        actorClientProfileId: null,
        branchId: session.user.branchId,
      },
    );

    return NextResponse.json(
      { data: workoutLogs, newBadges, autoGeneratedPostIds },
      { status: 201 },
    );
  } catch (error) {
    console.error('[POST /api/trainer/workouts] Error:', error);
    const { error: msg, code, status } = toErrorResponse(error);
    return NextResponse.json({ error: msg, code }, { status });
  }
}
