import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('@/lib/prisma', () => ({
  prisma: {
    clientProfile: { findFirst: vi.fn() },
    communityPost: {
      findFirst: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
    },
    communityReaction: {
      findUnique: vi.fn(),
      create: vi.fn(),
      delete: vi.fn(),
    },
    communityComment: {
      findFirst: vi.fn(),
      create: vi.fn(),
      delete: vi.fn(),
    },
  },
}));

vi.mock('@/lib/audit', () => ({ auditLog: vi.fn() }));

import { prisma } from '@/lib/prisma';
import * as community from '@/services/community.service';

const BRANCH = 'branch-1';
const ACTOR = 'actor-1';
const CLIENT = 'client-1';
type Mock = ReturnType<typeof vi.fn>;

beforeEach(() => vi.clearAllMocks());

// ─── Feed Pagination ────────────────────────────────────────────────

describe('getFeed', () => {
  function makePosts(count: number) {
    return Array.from({ length: count }, (_, i) => ({
      id: `post-${i + 1}`,
      branchId: BRANCH,
      isHidden: false,
      createdAt: new Date(2026, 4, 8 - i),
    }));
  }

  it('returns nextCursor=null when posts fit within the limit', async () => {
    (prisma.communityPost.findMany as Mock).mockResolvedValue(makePosts(5));

    const result = await community.getFeed({ branchId: BRANCH, limit: 10 });

    expect(result.posts).toHaveLength(5);
    expect(result.nextCursor).toBeNull();
  });

  it('returns nextCursor when there is another page', async () => {
    // Service queries `take: limit + 1`. If 11 come back, hasNextPage = true.
    (prisma.communityPost.findMany as Mock).mockResolvedValue(makePosts(11));

    const result = await community.getFeed({ branchId: BRANCH, limit: 10 });

    expect(result.posts).toHaveLength(10);
    expect(result.nextCursor).toBe('post-10');
  });

  it('forwards cursor to Prisma when supplied', async () => {
    (prisma.communityPost.findMany as Mock).mockResolvedValue([]);

    await community.getFeed({ branchId: BRANCH, cursor: 'post-5', limit: 5 });

    expect(prisma.communityPost.findMany).toHaveBeenCalledWith(
      expect.objectContaining({
        cursor: { id: 'post-5' },
        take: 6, // limit + 1
      }),
    );
  });

  it('filters out hidden posts and is branch-scoped', async () => {
    (prisma.communityPost.findMany as Mock).mockResolvedValue([]);

    await community.getFeed({ branchId: BRANCH });

    expect(prisma.communityPost.findMany).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { branchId: BRANCH, isHidden: false },
      }),
    );
  });

  it('uses a default limit of 20 when none provided', async () => {
    (prisma.communityPost.findMany as Mock).mockResolvedValue([]);

    await community.getFeed({ branchId: BRANCH });

    expect(prisma.communityPost.findMany).toHaveBeenCalledWith(
      expect.objectContaining({ take: 21 }),
    );
  });
});

// ─── createPost ─────────────────────────────────────────────────────

describe('createPost', () => {
  it('throws 404 when client not in branch', async () => {
    (prisma.clientProfile.findFirst as Mock).mockResolvedValue(null);

    await expect(
      community.createPost({
        branchId: BRANCH,
        clientProfileId: 'c-other',
        content: 'hi',
        actorId: ACTOR,
      }),
    ).rejects.toMatchObject({ code: 'NOT_FOUND', statusCode: 404 });
  });

  it('persists isAutoGenerated flag for auto-posts', async () => {
    (prisma.clientProfile.findFirst as Mock).mockResolvedValue({ id: CLIENT });
    (prisma.communityPost.create as Mock).mockResolvedValue({
      id: 'post-auto',
      isAutoGenerated: true,
    });

    await community.createPost({
      branchId: BRANCH,
      clientProfileId: CLIENT,
      exerciseId: 'ex-1',
      weightKg: 100,
      reps: 5,
      isAutoGenerated: true,
      actorId: ACTOR,
    });

    expect(prisma.communityPost.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          isAutoGenerated: true,
          exerciseId: 'ex-1',
          weightKg: 100,
        }),
      }),
    );
  });

  it('defaults isAutoGenerated to false when omitted', async () => {
    (prisma.clientProfile.findFirst as Mock).mockResolvedValue({ id: CLIENT });
    (prisma.communityPost.create as Mock).mockResolvedValue({ id: 'post-1' });

    await community.createPost({
      branchId: BRANCH,
      clientProfileId: CLIENT,
      content: 'manual post',
      actorId: ACTOR,
    });

    expect(prisma.communityPost.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ isAutoGenerated: false }),
      }),
    );
  });
});

// ─── deletePost ─────────────────────────────────────────────────────

describe('deletePost', () => {
  it('throws 404 when post not found', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue(null);

    await expect(
      community.deletePost({
        postId: 'post-x',
        branchId: BRANCH,
        actorClientProfileId: CLIENT,
        actorId: ACTOR,
      }),
    ).rejects.toMatchObject({ code: 'NOT_FOUND', statusCode: 404 });
  });

  it('forbids deletion when caller is not the post owner', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({
      id: 'post-1',
      clientProfileId: 'someone-else',
    });

    await expect(
      community.deletePost({
        postId: 'post-1',
        branchId: BRANCH,
        actorClientProfileId: CLIENT,
        actorId: ACTOR,
      }),
    ).rejects.toMatchObject({ code: 'FORBIDDEN', statusCode: 403 });
    expect(prisma.communityPost.update).not.toHaveBeenCalled();
  });

  it('soft-hides the post on owner deletion', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({
      id: 'post-1',
      clientProfileId: CLIENT,
    });
    (prisma.communityPost.update as Mock).mockResolvedValue({});

    await community.deletePost({
      postId: 'post-1',
      branchId: BRANCH,
      actorClientProfileId: CLIENT,
      actorId: ACTOR,
    });

    expect(prisma.communityPost.update).toHaveBeenCalledWith({
      where: { id: 'post-1' },
      data: { isHidden: true },
    });
  });
});

// ─── toggleReaction (uniqueness) ────────────────────────────────────

describe('toggleReaction', () => {
  it('throws 404 when post missing or hidden', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue(null);

    await expect(
      community.toggleReaction({ postId: 'post-x', branchId: BRANCH, clientProfileId: CLIENT }),
    ).rejects.toMatchObject({ code: 'NOT_FOUND', statusCode: 404 });
  });

  it('creates a reaction when none exists (reacted: true)', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({ id: 'post-1' });
    (prisma.communityReaction.findUnique as Mock).mockResolvedValue(null);
    (prisma.communityReaction.create as Mock).mockResolvedValue({ id: 'r-new' });

    const result = await community.toggleReaction({
      postId: 'post-1',
      branchId: BRANCH,
      clientProfileId: CLIENT,
    });

    expect(result).toEqual({ reacted: true });
    expect(prisma.communityReaction.create).toHaveBeenCalledWith({
      data: { postId: 'post-1', clientProfileId: CLIENT },
    });
    expect(prisma.communityReaction.delete).not.toHaveBeenCalled();
  });

  it('removes the existing reaction (reacted: false) — same client cannot react twice', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({ id: 'post-1' });
    (prisma.communityReaction.findUnique as Mock).mockResolvedValue({ id: 'r-existing' });
    (prisma.communityReaction.delete as Mock).mockResolvedValue({});

    const result = await community.toggleReaction({
      postId: 'post-1',
      branchId: BRANCH,
      clientProfileId: CLIENT,
    });

    expect(result).toEqual({ reacted: false });
    expect(prisma.communityReaction.delete).toHaveBeenCalledWith({ where: { id: 'r-existing' } });
    expect(prisma.communityReaction.create).not.toHaveBeenCalled();
  });

  it('uses the unique compound key (postId, clientProfileId) for the lookup', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({ id: 'post-1' });
    (prisma.communityReaction.findUnique as Mock).mockResolvedValue(null);
    (prisma.communityReaction.create as Mock).mockResolvedValue({ id: 'r-new' });

    await community.toggleReaction({
      postId: 'post-1',
      branchId: BRANCH,
      clientProfileId: CLIENT,
    });

    expect(prisma.communityReaction.findUnique).toHaveBeenCalledWith({
      where: { postId_clientProfileId: { postId: 'post-1', clientProfileId: CLIENT } },
    });
  });
});

// ─── addComment / deleteComment ─────────────────────────────────────

describe('addComment', () => {
  it('throws 404 when post missing or hidden', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue(null);

    await expect(
      community.addComment({
        postId: 'post-x',
        branchId: BRANCH,
        clientProfileId: CLIENT,
        content: 'nice',
        actorId: ACTOR,
      }),
    ).rejects.toMatchObject({ code: 'NOT_FOUND', statusCode: 404 });
  });

  it('creates a comment on a visible post', async () => {
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({ id: 'post-1' });
    (prisma.communityComment.create as Mock).mockResolvedValue({ id: 'cmt-1' });

    const result = await community.addComment({
      postId: 'post-1',
      branchId: BRANCH,
      clientProfileId: CLIENT,
      content: 'great PR!',
      actorId: ACTOR,
    });

    expect(result.id).toBe('cmt-1');
  });
});

describe('deleteComment', () => {
  it('throws 404 when comment not found in branch', async () => {
    (prisma.communityComment.findFirst as Mock).mockResolvedValue(null);

    await expect(
      community.deleteComment({
        commentId: 'cmt-x',
        branchId: BRANCH,
        actorClientProfileId: CLIENT,
        actorId: ACTOR,
      }),
    ).rejects.toMatchObject({ code: 'NOT_FOUND', statusCode: 404 });
  });

  it('forbids deletion for non-owner', async () => {
    (prisma.communityComment.findFirst as Mock).mockResolvedValue({
      id: 'cmt-1',
      clientProfileId: 'other-client',
    });

    await expect(
      community.deleteComment({
        commentId: 'cmt-1',
        branchId: BRANCH,
        actorClientProfileId: CLIENT,
        actorId: ACTOR,
      }),
    ).rejects.toMatchObject({ code: 'FORBIDDEN', statusCode: 403 });
    expect(prisma.communityComment.delete).not.toHaveBeenCalled();
  });

  it('deletes the comment when called by its owner', async () => {
    (prisma.communityComment.findFirst as Mock).mockResolvedValue({
      id: 'cmt-1',
      clientProfileId: CLIENT,
    });
    (prisma.communityComment.delete as Mock).mockResolvedValue({});

    await community.deleteComment({
      commentId: 'cmt-1',
      branchId: BRANCH,
      actorClientProfileId: CLIENT,
      actorId: ACTOR,
    });

    expect(prisma.communityComment.delete).toHaveBeenCalledWith({ where: { id: 'cmt-1' } });
  });
});
