import { describe, it, expect, vi, beforeEach } from 'vitest';

// ─── Mock all of workout.service's downstream deps ───────────────────

const mockTransaction = vi.fn();

vi.mock('@/lib/prisma', () => ({
  prisma: {
    sessionInstance: { findFirst: vi.fn() },
    exercise: { findMany: vi.fn(), findUnique: vi.fn() },
    workoutSet: { aggregate: vi.fn() },
    workoutLog: {},
    communityPost: { findFirst: vi.fn(), update: vi.fn() },
    $transaction: (...args: unknown[]) => mockTransaction(...args),
  },
}));

vi.mock('@/lib/audit', () => ({ auditLog: vi.fn() }));

vi.mock('@/services/badge.service', () => ({
  evaluatePRBadges: vi.fn().mockResolvedValue([]),
  evaluateWeightLiftedBadges: vi.fn().mockResolvedValue([]),
  evaluateExerciseMilestoneBadges: vi.fn().mockResolvedValue([]),
}));

const mockCreatePost = vi.fn();
vi.mock('@/services/community.service', () => ({
  createPost: (...args: unknown[]) => mockCreatePost(...args),
}));

import { prisma } from '@/lib/prisma';
import * as workout from '@/services/workout.service';

const BRANCH = 'branch-1';
const ACTOR = 'actor-1';
const SESSION_ID = 'sess-1';
const TRAINER_ID = 'trainer-1';
const CLIENT_ID = 'client-1';
type Mock = ReturnType<typeof vi.fn>;

beforeEach(() => {
  vi.clearAllMocks();

  (prisma.sessionInstance.findFirst as Mock).mockResolvedValue({
    id: SESSION_ID,
    branchId: BRANCH,
    trainerProfileId: TRAINER_ID,
    clientProfileId: CLIENT_ID,
    status: 'IN_PROGRESS',
  });

  // Both exercises will be valid in the existence check
  (prisma.exercise.findMany as Mock).mockResolvedValue([{ id: 'ex-bench' }, { id: 'ex-curl' }]);

  // Default: previous best is 100kg
  (prisma.workoutSet.aggregate as Mock).mockResolvedValue({
    _max: { weightKg: 100 },
  });

  // Default: no existing auto-post for the session+exercise
  (prisma.communityPost.findFirst as Mock).mockResolvedValue(null);
  (prisma.communityPost.update as Mock).mockResolvedValue({});

  // $transaction passes through to a fake `tx` that returns the workout logs.
  // Mirrors the upsert path in createWorkoutLogs: findMany existing → create
  // new → findUnique the final shape with relations.
  mockTransaction.mockImplementation(async (fn: (tx: unknown) => Promise<unknown>) => {
    const finalByLogId = new Map<string, unknown>();
    const buildLog = (
      exerciseId: string,
      sets: Array<{ setNumber: number; weightKg?: number | null; reps?: number | null }>,
    ) => ({
      id: `log-${exerciseId}`,
      exerciseId,
      exercise: {
        id: exerciseId,
        name: exerciseId === 'ex-bench' ? 'Bench Press' : 'Bicep Curl',
      },
      sets,
    });
    const tx = {
      workoutLog: {
        findMany: vi.fn().mockResolvedValue([]),
        deleteMany: vi.fn().mockResolvedValue({}),
        create: vi.fn().mockImplementation(
          async ({
            data,
          }: {
            data: {
              exerciseId: string;
              sets: {
                create: Array<{
                  setNumber: number;
                  weightKg?: number | null;
                  reps?: number | null;
                }>;
              };
            };
          }) => {
            const log = buildLog(data.exerciseId, data.sets.create);
            finalByLogId.set(log.id, log);
            return log;
          },
        ),
        findUnique: vi.fn().mockImplementation(async ({ where }: { where: { id: string } }) => {
          // Fall back to a default bench log so legacy test cases that didn't
          // wire up the create→findUnique chain still pass.
          return (
            finalByLogId.get(where.id) ??
            buildLog('ex-bench', [{ setNumber: 1, weightKg: 110, reps: 5 }])
          );
        }),
      },
      workoutSet: { deleteMany: vi.fn().mockResolvedValue({}) },
    };
    return fn(tx);
  });
});

const benchEntry = {
  exerciseId: 'ex-bench',
  orderIndex: 0,
  sets: [{ setNumber: 1, weightKg: 110, reps: 5 }],
};

describe('createWorkoutLogs — auto-post on compound PR (ADR-020)', () => {
  it('auto-posts when a new max-weight is set on a compound exercise', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    // Previous best: 100kg; new max: 110kg → triggers post
    (prisma.workoutSet.aggregate as Mock).mockResolvedValue({ _max: { weightKg: 100 } });
    mockCreatePost.mockResolvedValue({ id: 'post-auto' });

    const result = await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [benchEntry],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(mockCreatePost).toHaveBeenCalledTimes(1);
    expect(mockCreatePost).toHaveBeenCalledWith(
      expect.objectContaining({
        branchId: BRANCH,
        clientProfileId: CLIENT_ID,
        exerciseId: 'ex-bench',
        weightKg: 110,
        reps: 5,
        isAutoGenerated: true,
        actorId: ACTOR,
      }),
    );
    expect(result.autoGeneratedPostIds).toEqual(['post-auto']);
  });

  it('does NOT auto-post when the exercise is not compound', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: false });

    await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [{ ...benchEntry, exerciseId: 'ex-curl' }],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(mockCreatePost).not.toHaveBeenCalled();
  });

  it('does NOT auto-post when new max equals previous best (no PR)', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    // Previous best 110kg, new max 110kg → tied, not a PR
    (prisma.workoutSet.aggregate as Mock).mockResolvedValue({ _max: { weightKg: 110 } });

    await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [benchEntry],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(mockCreatePost).not.toHaveBeenCalled();
  });

  it('does NOT auto-post when new max is below previous best', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    (prisma.workoutSet.aggregate as Mock).mockResolvedValue({ _max: { weightKg: 130 } });

    await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [benchEntry],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(mockCreatePost).not.toHaveBeenCalled();
  });

  it('auto-posts on a first-ever lift for a compound exercise (previous best = 0)', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    // No prior logs → aggregate returns null
    (prisma.workoutSet.aggregate as Mock).mockResolvedValue({ _max: { weightKg: null } });
    mockCreatePost.mockResolvedValue({ id: 'post-first' });

    const result = await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [benchEntry],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(mockCreatePost).toHaveBeenCalledTimes(1);
    expect(result.autoGeneratedPostIds).toEqual(['post-first']);
  });

  it('does NOT auto-post when no weight is logged (e.g. duration-only exercise)', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    // The auto-post path is gated on maxWeight > 0; this entry has no weights
    const durationEntry = {
      exerciseId: 'ex-bench',
      orderIndex: 0,
      sets: [{ setNumber: 1, durationSec: 60 }],
    };

    // Override the tx mock so the returned log has no weighted sets
    mockTransaction.mockImplementationOnce(async (fn: (tx: unknown) => Promise<unknown>) => {
      const durationLog = {
        id: 'log-1',
        exerciseId: 'ex-bench',
        exercise: { id: 'ex-bench', name: 'Bench Press' },
        sets: [{ setNumber: 1, durationSec: 60, weightKg: null }],
      };
      const tx = {
        workoutLog: {
          findMany: vi.fn().mockResolvedValue([]),
          deleteMany: vi.fn().mockResolvedValue({}),
          create: vi.fn().mockResolvedValue(durationLog),
          findUnique: vi.fn().mockResolvedValue(durationLog),
        },
        workoutSet: { deleteMany: vi.fn().mockResolvedValue({}) },
      };
      return fn(tx);
    });

    await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [durationEntry],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(mockCreatePost).not.toHaveBeenCalled();
  });

  it('syncs an existing auto-post downward when a typo is corrected', async () => {
    // Repro: trainer fat-fingered "4515" into the weight field, auto-save
    // created a post at 4515, then the trainer corrected to 45. Pre-fix the
    // post was locked at 4515 forever because the dedup only updated upward.
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    (prisma.workoutSet.aggregate as Mock).mockResolvedValue({ _max: { weightKg: null } });
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({
      id: 'post-typo',
      weightKg: 4515,
      reps: null,
    });

    const result = await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [{ ...benchEntry, sets: [{ setNumber: 1, weightKg: 45, reps: 15 }] }],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(prisma.communityPost.update).toHaveBeenCalledWith({
      where: { id: 'post-typo' },
      data: { weightKg: 45, reps: 15 },
    });
    expect(mockCreatePost).not.toHaveBeenCalled();
    // Banner shouldn't re-fire on follow-up saves
    expect(result.autoGeneratedPostIds).toEqual([]);
  });

  it('syncs an existing auto-post upward when the lift improves mid-session', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    (prisma.workoutSet.aggregate as Mock).mockResolvedValue({ _max: { weightKg: 100 } });
    (prisma.communityPost.findFirst as Mock).mockResolvedValue({
      id: 'post-existing',
      weightKg: 105,
      reps: 5,
    });

    await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [benchEntry],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(prisma.communityPost.update).toHaveBeenCalledWith({
      where: { id: 'post-existing' },
      data: { weightKg: 110, reps: 5 },
    });
    expect(mockCreatePost).not.toHaveBeenCalled();
  });

  it('community-post failure does not break workout save', async () => {
    (prisma.exercise.findUnique as Mock).mockResolvedValue({ isCompound: true });
    (prisma.workoutSet.aggregate as Mock).mockResolvedValue({ _max: { weightKg: 50 } });
    mockCreatePost.mockRejectedValue(new Error('community service down'));

    // Should still resolve successfully
    const result = await workout.createWorkoutLogs({
      sessionInstanceId: SESSION_ID,
      exercises: [benchEntry],
      actorUserId: ACTOR,
      actorTrainerProfileId: TRAINER_ID,
      actorClientProfileId: null,
      branchId: BRANCH,
    });

    expect(result.workoutLogs).toBeDefined();
    expect(result.autoGeneratedPostIds).toEqual([]);
  });
});
